import { Product } from "./types/products";

export const sampleProducts: Product[] = [
  {
    name: "shirt",
    slug: "shirt1",
    image: "../images/shirt1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shirt",
    slug: "shirt2",
    image: "../images/shirt2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shirt",
    slug: "shirt3",
    image: "../images/shirt3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shirt",
    slug: "shirt4",
    image: "../images/shirt4.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt1",
    image: "../images/tshirt1.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt2",
    image: "../images/tshirt2.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt3",
    image: "../images/tshirt3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt4",
    image: "../images/tshirt4.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt5",
    image: "../images/tshirt5.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jacket",
    slug: "jacket1",
    image: "../images/jacket1.jpg",
    category: "jacket",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jacket",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jacket",
    slug: "jacket2",
    image: "../images/jacket2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jacket",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans1",
    image: "../images/jeans1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans2",
    image: "../images/jeans2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans3",
    image: "../images/jeans3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans4",
    image: "../images/jeans4.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans5",
    image: "../images/jeans5.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shoe",
    slug: "shoe1",
    image: "../images/shoe1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality shoe",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shoe",
    slug: "shoe2",
    image: "../images/shoe2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality shoe",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser1",
    image: "../images/trouser1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser2",
    image: "../images/trouser2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser3",
    image: "../images/trouser3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser4",
    image: "../images/trouser4.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser5",
    image: "../images/trouser5.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
];
