import { Product } from "./types/products";

export const sampleProducts: Product[] = [
  {
    name: "shirt",
    slug: "shirt1",
    image: "../image/shirt1,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shirt",
    slug: "shirt2",
    image: "../image/shirt2,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shirt",
    slug: "shirt3",
    image: "../image/shirt3,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shirt",
    slug: "shirt4",
    image: "../image/shirt4,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt1",
    image: "../image/tshirt1,",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt2",
    image: "../image/tshirt2,",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt3",
    image: "../image/tshirt3,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt4",
    image: "../image/tshirt4,",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "tshirt",
    slug: "tshirt5",
    image: "../image/tshirt5,",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jacket",
    slug: "jacket1",
    image: "../image/jacket1,",
    category: "jacket",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jacket",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jacket",
    slug: "jacket2",
    image: "../image/jacket2,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jacket",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans1",
    image: "../image/jeans1,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans2",
    image: "../image/jeans2,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans3",
    image: "../image/jeans3,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans4",
    image: "../image/jeans4,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "jeans",
    slug: "jeans5",
    image: "../image/jeans5,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shoe",
    slug: "shoe1",
    image: "../image/shoe1,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality shoe",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "shoe",
    slug: "shoe2",
    image: "../image/shoe2,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality shoe",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser1",
    image: "../image/trouser1,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser2",
    image: "../image/trouser2,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser3",
    image: "../image/trouser3,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser4",
    image: "../image/trouser4,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "trouser",
    slug: "trouser5",
    image: "../image/trouser5,",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 10,
  },
];
