import { Product } from "./types/products";

const sampleProducts: Product[] = [
  {
    name: "shirt",
    slug: "shirt1",
    image: "../images/shirt1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 110,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 218,
  },
  {
    name: "shirt",
    slug: "shirt2",
    image: "../images/shirt2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 155,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4,
    numReviews: 105,
  },
  {
    name: "shirt",
    slug: "shirt3",
    image: "../images/shirt3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 165,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.2,
    numReviews: 106,
  },
  {
    name: "shirt",
    slug: "shirt4",
    image: "../images/shirt4.jpg",
    category: "shirt",
    brand: "Nike",
    price: 175,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.6,
    numReviews: 1056,
  },
  {
    name: "tshirt",
    slug: "tshirt1",
    image: "../images/tshirt1.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 185,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 3.9,
    numReviews: 178,
  },
  {
    name: "tshirt",
    slug: "tshirt2",
    image: "../images/tshirt2.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 195,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 3.4,
    numReviews: 176,
  },
  {
    name: "tshirt",
    slug: "tshirt3",
    image: "../images/tshirt3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 205,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 5,
    numReviews: 185,
  },
  {
    name: "tshirt",
    slug: "tshirt4",
    image: "../images/tshirt4.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4.5,
    numReviews: 154,
  },
  {
    name: "tshirt",
    slug: "tshirt5",
    image: "../images/tshirt5.jpg",
    category: "tshirt",
    brand: "Nike",
    price: 140,
    countInStock: 10,
    description: "High Quality tshirt",
    rating: 4,
    numReviews: 176,
  },
  {
    name: "jacket",
    slug: "jacket1",
    image: "../images/jacket1.jpg",
    category: "jacket",
    brand: "Nike",
    price: 176,
    countInStock: 10,
    description: "High Quality jacket",
    rating: 3,
    numReviews: 187,
  },
  {
    name: "jacket",
    slug: "jacket2",
    image: "../images/jacket2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jacket",
    rating: 5,
    numReviews: 156,
  },
  {
    name: "jeans",
    slug: "jeans1",
    image: "../images/jeans1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 127,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 3.6,
    numReviews: 109,
  },
  {
    name: "jeans",
    slug: "jeans2",
    image: "../images/jeans2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 122,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 5,
    numReviews: 176,
  },
  {
    name: "jeans",
    slug: "jeans3",
    image: "../images/jeans3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 190,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.5,
    numReviews: 132,
  },
  {
    name: "jeans",
    slug: "jeans4",
    image: "../images/jeans4.jpg",
    category: "shirt",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4,
    numReviews: 123,
  },
  {
    name: "jeans",
    slug: "jeans5",
    image: "../images/jeans5.jpg",
    category: "shirt",
    brand: "Nike",
    price: 210,
    countInStock: 10,
    description: "High Quality jeans",
    rating: 4.3,
    numReviews: 165,
  },
  {
    name: "shoe",
    slug: "shoe1",
    image: "../images/shoe1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 130,
    countInStock: 10,
    description: "High Quality shoe",
    rating: 4,
    numReviews: 152,
  },
  {
    name: "shoe",
    slug: "shoe2",
    image: "../images/shoe2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 140,
    countInStock: 10,
    description: "High Quality shoe",
    rating: 4.8,
    numReviews: 91,
  },
  {
    name: "trouser",
    slug: "trouser1",
    image: "../images/trouser1.jpg",
    category: "shirt",
    brand: "Nike",
    price: 170,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 87,
  },
  {
    name: "trouser",
    slug: "trouser2",
    image: "../images/trouser2.jpg",
    category: "shirt",
    brand: "Nike",
    price: 160,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.4,
    numReviews: 57,
  },
  {
    name: "trouser",
    slug: "trouser3",
    image: "../images/trouser3.jpg",
    category: "shirt",
    brand: "Nike",
    price: 150,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.1,
    numReviews: 108,
  },
  {
    name: "trouser",
    slug: "trouser4",
    image: "../images/trouser4.jpg",
    category: "shirt",
    brand: "Nike",
    price: 140,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 3.9,
    numReviews: 114,
  },
  {
    name: "trouser",
    slug: "trouser5",
    image: "../images/trouser5.jpg",
    category: "shirt",
    brand: "Nike",
    price: 130,
    countInStock: 10,
    description: "High Quality trouser",
    rating: 4.5,
    numReviews: 100,
  },
];

export default sampleProducts;
